runtime: python39

env_variables:
  FLASK_ENV: production
  HF_TOKEN: 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

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.9

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 5

handlers:
- url: /api/.*
  script: auto
  
- url: /.*
  script: auto